apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inventory-service.configMapName" . }}
  labels:
    {{- include "inventory-service.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  DB_HOST: {{ .Values.global.postgres.host | quote }}
  DB_PORT: {{ .Values.global.postgres.port | quote }}
  DB_USER: {{ .Values.global.postgres.user | quote }}
  REDIS_HOST: {{ .Values.global.redis.host | quote }}
  REDIS_PORT: {{ .Values.global.redis.port | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.global.kafka.bootstrapServers | quote }}
  OTEL_HOST: {{ .Values.global.otel.host | quote }}
  DEPLOY_ENV: {{ .Values.global.deployEnv | quote }}
