{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inventory-service.secretName" . }}
  labels:
    {{- include "inventory-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.global.postgres.password | quote }}
{{- end }}
